---
title: "Abraham Gihawi - Curriculum Vitae"
author: Abraham Gihawi
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: [ 'resume', 'css/styles.css', 'css/academicons.css', 'css/index_files/font-awesome-5.1.0/css/all.css']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
knit: pagedown::chrome_print
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
#remotes::install_github("rstudio/fontawesome")
library(fontawesome)
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> [AbrahamGihawi@hotmail.com](mailto::a.gihawi@uea.ac.uk)
- <i class="fa fa-github"></i> [Agihawi](https://github.com/Agihawi)
- <i class="fa fa-twitter"></i> [\@AbrahamGihawi](https://twitter.com/AbrahamGihawi)
- <i class="fa fa-phone"></i> +44 7793068331
- <i class="ai ai-orcid"></i> [ORCID](https://orcid.org/0000-0002-3676-5561)
- <i class="fab fa-linkedin-in"></i> [LinkedIn](https://www.linkedin.com/in/abraham-gihawi-887954a6/)
- <i class="ai ai-google-scholar"></i> [Google Scholar](https://scholar.google.co.uk/citations?user=CzHmHBYAAAAJ&hl=en&oi=ao)


Skills {#skills}
--------------------------------------------------------------------------------
**Programming:** R, Python, Unix

- Computational Pipelines
- Microbial Bioinformatics 
- High Performance Computing
- Dimensionality Reduction
- Translational Cancer Research


Conferences 
--------------------------------------------------------------------------------

Posters:

[EACR Bioinformatics in Cancer, 2021](https://github.com/UEA-Cancer-Genetics-Lab/EACR_Bioinformatics_2021/blob/master/Poster.pdf) <br>
[NCRN Symposium, 2020](https://agihawi.github.io/ncrn_poster/) `r fa("trophy", fill = "gold")` <br>
[Genomics England, 2019](https://github.com/Agihawi/Gel_Conference_Poster_1/blob/master/Posterdown.pdf) <br>
[EMBL Heidelberg, 2018](https://www.embo-embl-symposia.org/symposia/2018/EES18-09/index.html)


Talks:

[ICCMG5 2021](https://clinicalmetagenomics.org/teams/abraham-gihawi/) <br>
[NCRN, 2021](https://twitter.com/CancerInNorwich/status/1353738228625514500) <br>
UEA PGR Conference, 2018

References
--------------------------------------------------------------------------------
[Prof. Daniel Brewer](https://people.uea.ac.uk/d_brewer) D.Brewer@uea.ac.uk

[Prof. Colin Cooper](https://people.uea.ac.uk/colin_cooper) Colin.Cooper@uea.ac.uk


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Code available: [github.com/Agihawi/Gihawi_CV](https://github.com/Agihawi/Gihawi_CV)

Last updated: `r Sys.Date()`



Main
================================================================================

Abraham Gihawi {#title}
--------------------------------------------------------------------------------

### Computational Biologist

Multidisciplinary bioinformatician with a keen interest in cancer and pathogen genomics. During my PhD, developed [containerised computational pipelines](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1819-8) to allow for the automated and reproducible retrieval of pathogenic sequences from within human tissue DNA sequencing data. Also formulated hypotheses as to how pathogens influence tumour biology by searching for [clinical associations](https://doi.org/10.1016/j.euo.2022.03.006). 

Academia {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Senior Research Associate in Bioinformatics

PanProstate Cancer Group Bioinformatician

UEA

2022 - 2023

This role beginning July 2022 will entail harmonising and analysing clinical data from international sources within the Pan-Prostate Cancer Group. I am planning to develop and maintain databases to facilitate the robust dissemination of data to collaborators. These resources will be used to investigate the rich content of the PPCG including microbial composition.


### Senior Bioinformatics Officer

Cancer Genetics and Metagenomics

UEA

2021 - Aug 2022

This position stemmed from a successful grant application using insights obtained during my PhD. This project uses whole genome and RNA sequencing data from the Pan-Prostate Cancer Group (PPCG) to identify how microbes might be associated with aggressive prostate cancer.

### PhD Computational Biology

Thesis: *"Searching for Pathogens in Cancer Sequence Data"*

UEA

2021 - 2017

Supervisors: Prof. Daniel Brewer, Dr. Ghanasyam Rallapalli, Dr. Richard Leggett, Dr. Rachel Hurst, Prof. Colin Cooper

In this position I developed benchmarked approaches to search for microbial nucleic acids within human tissue sequence data. I applied these pipelines to multiple datasets including Genomics England's 100,000 Genomes Project. This has lead to characterising the microbial landscape of the tumour microenvironment. I have also investigated human and metagenomic transcriptomic data from exosomal fractions of urine from patients under investigation for prostate cancer. This has revealed some potentially impactful associations with clinical metadata and generated hypotheses regarding how pathogens interact with tumours. Additionally this work has lead to successful grant applications and intellectual property.

#### Technical Skills:
Proficiency in various programming languages (R, Python and Unix), Developing and applying computational pipelines (Snakemake), handling large quantities of sequencing data, containerising software, reproducible research, microbial bioinformatics, high performance computing, dimensionality reduction, version control software, metagenomic assembly, assembly of bacterial isolates, prediction of metabolic pathways, human RNA differential expression, analysis of 16S ribosomal RNA sequencing data, phylogenetics, clustering algorithms, machine learning approaches (random forest, boruta), survival analysis, submission of sequence data to public archives

#### Other Skills:
Scientific writing, problem solving, critical thinking, project management and organisation, presentation skills, translational research, multidisciplinary collaboration.


### MSc, Cancer Therapeutics - Distinction - 80%

Project: PHLDA1 in FGFR Inhibitor Resistant Cancer

QMUL

2017 - 2015

Supervisors: Prof. Richard Grose

In this course I delved into the depths of how we can leverage the underlying science of cancer for clinical benefit. I studied a range of subjects relating to cancer including: cancer biology ablative therapies, cancer pathology, cancer pharmacology, cancer prevention and screening, molecular diagnostics and therapeutics, drug development molecular diagnostics and therapeutics, molecular targeted therapies for haematological malignancies and genomic approaches to human disease. My project involved characterising *PHLDA1* which was shown to be the most significantly downregulated gene in fibroblast growth factor receptor (FGFR) inhibitor resistant endometrial cancer. 

#### Technical Skills:

Mammalian cell culture, western blotting, 3D organotypic culture models, clonogenic assays, efficient laboratory work, analysing immunofluorescence images, searching for synergistic relationship between candidate drugs.

#### Other Skills:

Time management, Student representative for the course, conveying the concerns of both on-site students as well as remote leaners to faculty staff. 


### BSc (hons) Biomedical Science - 69%

Project: A Portable Test for Bacteria & Urobilinogen in Urine

Lincoln

2014 - 2011

Supervisor: Dr Jose Gonzalez-Rodriguez

This course, accredited by the Institute of Biomedical Science (IBMS) provided me with a base level of knowledge in the biomedical field. I read several topics including: Pharmacology, Anatomy & Physiology, Biochemistry, Molecular Biology, Genetics, Health & Disease, Microbiology, Immunology, General Good Laboratory Practice, Research Skills. Seeking to develop my scientific independence, I selected the research topic "Developing a Portable Assay for the Detection of Bacteria & Urobilinogen in Urine" for my final year project. In this project I developed assays for bacteria and urobilinogen in urine and investigated whether mobile phone cameras could accurately quantify these analytes.

#### Technical Skills:

Good laboratory practice, research methods, microbiological culture, gram staining, independent scientific research, microtomy, microscopy, blood cell morphology, tissue staining and histology, electrophoresis, pipetting, fluorescent *in situ* hybridization, latex agglutination assays.

Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Medical Laboratory Assistant

Royal Sussex County Hospital

Brighton

2017 - 2015

In this position I was responsible for implementing and conducting laboratory processing of samples for research studies and clinical trials. My day to day duties involved collaborating with a wide range of clinical and non-clinical staff, maintaining laboratory equipment sample processing such as centrifugation, blood smears, flow cytometry and isolation of peripheral blood mononuclear cells. One of the ways this position stimulated my interest in cancer was by carrying out a trial for the Endopredict `r fa("registered")` prognostic qPCR expression assay for patients with HER2- ER+ breast cancer.

### Health Advisor NHS 111

Care UK 

Dorking

2015 - 2014

In this position I utilised my knowledge to assist patients with their medical concerns. I triaged them over the telephone and directed them towards the appropriate medical services. This post allowed me to witness the human element of medical care. I handled a wide range of clinical events ranging from physical trauma to mental health crises, safeguarding concerns, urinary tract infections to symptoms of metastatic cancer. 

### NHS Experience Placements

Princess Diana & Scunthorpe General

Grimsby & Scunthorpe

2014 - 2013

These work experience placements allowed me to witness many of the different aspects of patient care by assisting staff in a range of departments including: Radiology, Nuclear Medicine, Cardiology and Pathology (Biochemistry, Haematology, Transfusion, Andrology, Virology). This was an incredibly useful set of experiences that I feel has given me a holistic perspective on patient care.

First Author Publications {data-icon=book}
--------------------------------------------------------------------------------

### <i class="ai ai-open-access"></i> Microbiomes of Urine and the Prostate Are Linked to Human Prostate Cancer Risk Groups

European Urology Oncology

DOI: [10.1016/j.euo.2022.03.006](https://doi.org/10.1016/j.euo.2022.03.006)

2022

Rachel Hurst, Emma Meader, **Abraham Gihawi** Ghanasyam Rallapalli... Colin Cooper.



### <i class="ai ai-open-access"></i> SEPATH: benchmarking the search for pathogens in human tissue whole genome sequence data leads to template pipelines 


Genome Biology

DOI: [10.1186/s13059-019-1819-8](https://doi.org/10.1186/s13059-019-1819-8)

2019


**Abraham Gihawi**, Ghanasyam Rallapalli, Rachel Hurst... Daniel S. Brewer 


Additional Publications {data-icon=book}
--------------------------------------------------------------------------------

### <i class="ai ai-open-access"></i> Potential for Diagnosis of Infectious Disease from the 100,000 Genomes Project Metagenomic Dataset: Recommendations for Reporting Results

Wellcome Open Research

DOI: [10.12688/wellcomeopenres.15499.1](https://doi.org/10.12688/wellcomeopenres.15499.1)

2019

Gkikas Magiorkinis... **Abraham Gihawi**... Colin Cooper.


Grants {data-icon=money}
--------------------------------------------------------------------------------

#### "Unraveling how bacterial infection drives the development of aggressive prostate cancer" - Prostate Cancer UK

I was a co-applicant alongside Prof. Daniel Brewer for this grant to provide financial support to fund a Senior Bioinformatics Officer for 18 months. This grant is responsible for my current position. Value: £77,925.

#### "The Role of Bacterial Infection in the development of Human Prostate Cancer" - Bob Champion Cancer Trust

I was Co-Applicant alongside Dr Rachel Hurst, Prof. Daniel Brewer and Prof. Colin Cooper. This grant finances laboratory investigations into the role of bacterial infection in the development of human prostate cancer. Bob Champion Cancer Trust. Value: £87,634.


Conferences and Presentations {data-icon=file-powerpoint}
--------------------------------------------------------------------------------

Presenting scientific data is something that I find valuable and I have been fortunate to be able to present to a diverse range of audiences in recent years. This includes planning and preparing outreach to schools, producing award winning scientific posters and I was an invited speaker at the [5th International Conference on Clinical Metagenomics](https://clinicalmetagenomics.org/teams/abraham-gihawi/) held in Geneva. Other international conferences I have attended and presented posters at include: The Human Microbiome, European Molecular Biology Laboratory Heidelberg (2018), and Bioinformatics in Cancer, virtual conference (2021)

One of my most successful presentations won a runner-up [award](https://twitter.com/CancerInNorwich/status/1303009991255887873) for best poster after producing an [interactive poster](https://t.co/aX1m9UiomG?amp=1) (code available on [GitHub](https://github.com/Agihawi/ncrn_poster)) and giving a talk on the content to the audience. The posters were also hosted online which attracted a [wide range of participation and engagement](https://padlet.com/swest116/NCRNposter).

Other presentations I have given include a [poster presentation](https://github.com/Agihawi/Gel_Conference_Poster_1/blob/master/Posterdown.pdf) (code available on [GitHub](https://github.com/Agihawi/Gel_Conference_Poster_1) for a Genomics England research symposium, which included experienced scientists and project participants. Additionally, I have given talks and presented posters at our local university's postgraduate researcher events as well as presenting frequently within my laboratory group meetings and departments bioinformatics meetings. In these bioinformatics meetings I have instigated programming challenges which I host fortnightly to enable us to discuss various aspects of scientific coding and problem solving.


Other {data-icon=balance-scale}
--------------------------------------------------------------------------------

**Peer Review:** Genome Biology (BMC), Genomics (Elsevier), Bioinformatics Advances (Oxford University Press)


